<a href="https://colab.research.google.com/github/Talibsid-1996/Movies-Recommended-System/blob/main/Movie_Recommended_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Project Name**  --  Movie Recommender System.ipynb

Hey there! Today we will go about creating a movie recommendation system using data from the TMDB dataset. W will do content based filtering.
Lets start off with reading our dataset!

In [ ]:
# import libraries
import pandas as pd
import numpy as np

My GitHub Link here.

Github Link - https://github.com/Talibsid-1996

In [ ]:
# Mount your google drive in google colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Loading the data
movies = pd.read_csv('/content/drive/MyDrive/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/drive/MyDrive/tmdb_5000_credits.csv')

In [ ]:
# firstlook of data
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
# merging of both dataset
movies=movies.merge(credits,on = 'title')

In [ ]:
# shape of data
movies.shape

(4809, 23)

In [ ]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
movies.head(1).T

                                                                      0
budget                                                        237000000
genres                [{"id": 28, "name": "Action"}, {"id": 12, "nam...
homepage                                    http://www.avatarmovie.com/
id                                                                19995
keywords              [{"id": 1463, "name": "culture clash"}, {"id":...
original_language                                                    en
original_title                                                   Avatar
overview              In the 22nd century, a paraplegic Marine is di...
popularity                                                   150.437577
production_companies  [{"name": "Ingenious Film Partners", "id": 289...
production_countries  [{"iso_3166_1": "US", "name": "United States o...
release_date                                                 2009-12-10
revenue                                                      2787965087
runtime                                                           162.0
spoken_languages      [{"iso_639_1": "en", "name": "English"}, {"iso...
status                                                         Released
tagline                                     Enter the World of Pandora.
title                                                            Avatar
vote_average                                                        7.2
vote_count                                                        11800
movie_id                                                          19995
cast                  [{"cast_id": 242, "character": "Jake Sully", "...
crew                  [{"credit_id": "52fe48009251416c750aca23", "de...

In [ ]:
# selecting useful features
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [ ]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [ ]:
# checking missing values
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
# dropping null values
movies.dropna(inplace=True)

In [ ]:
# checking dupliated data
movies.duplicated().sum()

0

In [ ]:
# creating function for fetaures extraction
import ast
def convert(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [ ]:
# apply function
movies['genres'] = movies['genres'].apply(convert)

In [ ]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
# checking keywords features
movies.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [ ]:
# apply convert function to keywords
movies['keywords'] = movies['keywords'].apply(convert)

In [ ]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united statesâ€“mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [ ]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [ ]:
# creating a function for extracting info from cast and crew
def convert3(obj):
  L=[]
  counter = 0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'])
      counter+=1
    else:
      break  
  return L

In [ ]:
# Apply the convert3 function 
movies['cast']=movies['cast'].apply(convert3)

In [ ]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [ ]:
# creating a function for fetching director name
def fetch_direc(obj):
  L=[]
  
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':

      L.append(i['name'])
      break  
  return L

In [ ]:
# Apply fetch director function
movies['crew'] = movies['crew'].apply(fetch_direc)

In [ ]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [ ]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [ ]:
# changing overview from string to a list
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [ ]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [ ]:

movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(' ','') for i in x])
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(' ','') for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(' ','') for i in x])
movies['cast'] = movies['crew'].apply(lambda x:[i.replace(' ','') for i in x])

In [ ]:
# adding all the columns

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [ ]:
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'JamesCameron',
 'James Cameron']

In [ ]:
# creating a new dataframe with these features
new_df = movies[['movie_id','title','tags']]
new_df.head(2)

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."

In [ ]:
# changing list to string
new_df['tags'] = new_df['tags'].apply(lambda x:' '.join(x))

<ipython-input-56-68a616cd60db>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:' '.join(x))

In [ ]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d JamesCameron James Cameron'

In [ ]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

#Stemming

In [ ]:
import nltk

In [ ]:
#stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))

  return ' '.join(y)

In [ ]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-63-be18a4346d89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

# Vectorization

In [ ]:
# removing stop words
from sklearn .feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
cv.get_feature_names()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '150',
 '16',
 '17',
 '17th',
 '18',
 '1890',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1995',
 '1997',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2000',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'abandon',
 'abduct',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abram',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrian',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alejandro',
 'alex',
 'alexand',
 'alfr',
 'alfredhitchcock',
 'algeria',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'alleg',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allow',
 'alon',
 'alongsid',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'ander',
 'anderson',
 'andi',
 'andrew',
 'andrewniccol',
 'android',
 'andy',
 'andyfickman',
 'ang',
 'angel',
 'angela',
 'angeles',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'ann',
 'anna',
 'annabel',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoin',
 'antoinefuqua',
 'anton',
 'antonio',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'aquarium',
 'arab',
 'arbitrarylaw',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'armstrong',
 'army',
 'arnold',
 'aronofski',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becker',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'bend',
 'beneath',
 'benefit',
 'benjamin',
 'bennett',
 'bent',
 'berg',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'better',
 'betti',
 'beverli',
 'bibl',
 'biblic',
 'bicker',
 'bicycl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'bilbo',
 'billi',
 'billionair',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blake',
 'blame',
 'blaze',
 'blend',
 'bless',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blog',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'boring',
 'born',
 'borrow',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'bowl',
 'bowman',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boyl',
 'boys',
 'brad',
 'brain',
 'brainwash',
 'branagh',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brent',
 'brett',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brutal',
 'bryan',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bum',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burger',
 'burglar',
 'buri',
 'burn',
 'burton',
 'bush',
 'busi',
 'business',
 'businessman',
 'businesswoman',
 'bust',
 'butch',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'bythewood',
 'cabin',
 'caesar',
 'cage',
 'cain',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'caribbean',
 'carjourney',
 'carl',
 'carlo',
 'carmen',
 'carol',
 'carolina',
 'carpent',
 'carrac',
 'carri',
 'cartel',
 'carter',
 'cartoon',
 'caruso',
 'case',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'catherin',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chan',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chloe',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chopra',
 'chosen',
 'chri',
 'chriscolumbu',
 'christ',
 'christian',
 'christin',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christophernolan',
 'chronicl',
 'chu',
 'chuck',
 'church',
 'cia',
 'cigarettesmok',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claud',
 'claudia',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clint',
 'clinteastwood',
 'cliqu',
 'clock',
 'clone',
 'clooney',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'coastal',
 'cocain',
 'cocki',
 'code',
 'codi',
 'coen',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'collaps',
 'collapse',
 'colleagu',
 'colleague',
 'collect',
 'collector',
 'colleg',
 'college',
 'collet',
 'collid',
 'collide',
 'collin',
 'collis',
 'colombia',
 'colon',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'columbu',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compound',
 'compromis',
 'compuls',
 'comput',
 'computer',
 'computerviru',
 'conan',
 'concentrationcamp',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connor',
 'conquer',
 'conrad',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convert',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'coppola',
 'cops',
 'coraci',
 'core',
 'corleon',
 'corner',
 'corp',
 ...]

#cosine similarity

In [ ]:

from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# apply similarity distance
simlarity = cosine_similarity(vectors)

In [ ]:
sorted(list(enumerate(simlarity[0])),reverse = True,key =lambda x : x[1])[1:6]

[(2409, 0.30692490702242564),
 (1216, 0.2811237422961876),
 (3730, 0.25715142542972574),
 (539, 0.254762332682534),
 (507, 0.25231028011870793)]

In [ ]:

def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distance = simlarity[movie_index]
  movies_list = sorted(list(enumerate(distance)),reverse = True,key =lambda x : x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [ ]:
list(new_df['title'].unique())

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',
 'TRON: Legacy',
 'Cars 2',
 'Green Lantern',
 'Toy Story 3',
 'Terminator Salvation',
 'Furious 7',
 'World War Z',
 'X-Men: Days of Future Past',
 'Star Trek Into Darkness',
 'Jack the Giant Slayer',
 'The Great Gatsby',
 'Prince of Persia: The Sands of Time',
 'Pacific Rim',
 'Transformers: Dark of the Moon',
 'Indiana Jones and the Kingdom of the Crystal Skull',
 'The Good Dinosaur',
 'Brave',
 'Star Trek Beyond',
 'WALLÂ·E',
 'Rush Hour 3',
 '2012',
 'A Christmas Carol',
 'Jupiter Ascending',
 'The Legend of Tarzan',
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 'X-Men: Apocalypse',
 'The Dark Knight',
 'Up',
 'Monsters vs Aliens',
 'Iron Man',
 'Hugo',
 'Wild Wild West',
 'The Mummy: Tomb of the Dragon Emperor',
 'Suicide Squad',
 'Evan Almighty',
 'Edge of Tomorrow',
 'Waterworld',
 'G.I. Joe: The Rise of Cobra',
 'Inside Out',
 'The Jungle Book',
 'Iron Man 2',
 'Snow White and the Huntsman',
 'Maleficent',
 'Dawn of the Planet of the Apes',
 'The Lovers',
 '47 Ronin',
 'Captain America: The Winter Soldier',
 'Shrek Forever After',
 'Tomorrowland',
 'Big Hero 6',
 'Wreck-It Ralph',
 'The Polar Express',
 'Independence Day: Resurgence',
 'How to Train Your Dragon',
 'Terminator 3: Rise of the Machines',
 'Guardians of the Galaxy',
 'Interstellar',
 'Inception',
 'Shin Godzilla',
 'The Hobbit: An Unexpected Journey',
 'The Fast and the Furious',
 'The Curious Case of Benjamin Button',
 'X-Men: First Class',
 'The Hunger Games: Mockingjay - Part 2',
 "The Sorcerer's Apprentice",
 'Poseidon',
 'Alice Through the Looking Glass',
 'Shrek the Third',
 'Warcraft',
 'Terminator Genisys',
 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 'Pearl Harbor',
 'Transformers',
 'Alexander',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Goblet of Fire',
 'Hancock',
 'I Am Legend',
 'Charlie and the Chocolate Factory',
 'Ratatouille',
 'Batman Begins',
 'Madagascar: Escape 2 Africa',
 'Night at the Museum: Battle of the Smithsonian',
 'X-Men Origins: Wolverine',
 'The Matrix Revolutions',
 'Frozen',
 'The Matrix Reloaded',
 'Thor: The Dark World',
 'Mad Max: Fury Road',
 'Angels & Demons',
 'Thor',
 'Bolt',
 'G-Force',
 'Wrath of the Titans',
 'Dark Shadows',
 'Mission: Impossible - Rogue Nation',
 'The Wolfman',
 'Bee Movie',
 'Kung Fu Panda 2',
 'The Last Airbender',
 'Mission: Impossible III',
 'White House Down',
 'Mars Needs Moms',
 'Flushed Away',
 'Pan',
 'Mr. Peabody & Sherman',
 'Troy',
 "Madagascar 3: Europe's Most Wanted",
 'Die Another Day',
 'Ghostbusters',
 'Armageddon',
 'Men in Black II',
 'Beowulf',
 'Kung Fu Panda 3',
 'Mission: Impossible - Ghost Protocol',
 'Rise of the Guardians',
 'Fun with Dick and Jane',
 'The Last Samurai',
 'Exodus: Gods and Kings',
 'Star Trek',
 'Spider-Man',
 'How to Train Your Dragon 2',
 'Gods of Egypt',
 'Stealth',
 'Watchmen',
 'Lethal Weapon 4',
 'Hulk',
 'G.I. Joe: Retaliation',
 'Sahara',
 'Final Fantasy: The Spirits Within',
 'Captain America: The First Avenger',
 'The World Is Not Enough',
 'Master and Commander: The Far Side of the World',
 'The Twilight Saga: Breaking Dawn - Part 2',
 'Happy Feet Two',
 'The Incredible Hulk',
 'The BFG',
 'The Revenant',
 'Turbo',
 'Rango',
 'Penguins of Madagascar',
 'The Bourne Ultimatum',
 'Kung Fu Panda',
 'Ant-Man',
 'The Hunger Games: Catching Fire',
 'Home',
 'War of the Worlds',
 'Bad Boys II',
 'Puss in Boots',
 'Salt',
 'Noah',
 'The Adventures of Tintin',
 'Harry Potter and the Prisoner of Azkaban',
 'Australia',
 'After Earth',
 'Dinosaur',
 'Night at the Museum: Secret of the Tomb',
 'Megamind',
 "Harry Potter and the Philosopher's Stone",
 'R.I.P.D.',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The Hunger Games: Mockingjay - Part 1',
 'The Da Vinci Code',
 'Rio 2',
 'X2',
 'Fast Five',
 'Sherlock Holmes: A Game of Shadows',
 'Clash of the Titans',
 'Total Recall',
 'The 13th Warrior',
 'The Bourne Legacy',
 'Batman & Robin',
 'How the Grinch Stole Christmas',
 'The Day After Tomorrow',
 'Mission: Impossible II',
 'The Perfect Storm',
 'Fantastic 4: Rise of the Silver Surfer',
 'Life of Pi',
 'Ghost Rider',
 'Jason Bourne',
 "Charlie's Angels: Full Throttle",
 'Prometheus',
 'Stuart Little 2',
 'Elysium',
 'The Chronicles of Riddick',
 'RoboCop',
 'Speed Racer',
 'How Do You Know',
 'Knight and Day',
 'Oblivion',
 'Star Wars: Episode III - Revenge of the Sith',
 'Star Wars: Episode II - Attack of the Clones',
 'Monsters, Inc.',
 'The Wolverine',
 'Star Wars: Episode I - The Phantom Menace',
 'The Croods',
 'Asterix at the Olympic Games',
 'Windtalkers',
 "The Huntsman: Winter's War",
 'Teenage Mutant Ninja Turtles',
 'Gravity',
 "Dante's Peak",
 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 'Fantastic Four',
 'Night at the Museum',
 'San Andreas',
 'Tomorrow Never Dies',
 'The Patriot',
 "Ocean's Twelve",
 'Mr. & Mrs. Smith',
 'Insurgent',
 'The Aviator',
 "Gulliver's Travels",
 'The Green Hornet',
 '300: Rise of an Empire',
 'The Smurfs',
 'Home on the Range',
 'Allegiant',
 'Real Steel',
 'The Smurfs 2',
 'Speed 2: Cruise Control',
 "Ender's Game",
 'Live Free or Die Hard',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Around the World in 80 Days',
 'Ali',
 'The Cat in the Hat',
 'I, Robot',
 'Kingdom of Heaven',
 'Stuart Little',
 'The Princess and the Frog',
 'The Martian',
 'The Island',
 'Town & Country',
 'Gone in Sixty Seconds',
 'Gladiator',
 'Minority Report',
 'Harry Potter and the Chamber of Secrets',
 'Casino Royale',
 'Planet of the Apes',
 'Terminator 2: Judgment Day',
 'Public Enemies',
 'American Gangster',
 'True Lies',
 'The Taking of Pelham 1 2 3',
 'Little Fockers',
 'The Other Guys',
 'Eraser',
 'Django Unchained',
 'The Hunchback of Notre Dame',
 "The Emperor's New Groove",
 'The Expendables 2',
 'National Treasure',
 'Eragon',
 'Where the Wild Things Are',
 'Epic',
 'The Tourist',
 'End of Days',
 'Blood Diamond',
 'The Wolf of Wall Street',
 'Batman Forever',
 'Starship Troopers',
 'Cloud Atlas',
 "Legend of the Guardians: The Owls of Ga'Hoole",
 'Catwoman',
 'Hercules',
 'Treasure Planet',
 'Land of the Lost',
 'The Expendables 3',
 'Point Break',
 'Son of the Mask',
 'In the Heart of the Sea',
 'The Adventures of Pluto Nash',
 'Green Zone',
 'The Peanuts Movie',
 'The Spanish Prisoner',
 'The Mummy Returns',
 'Gangs of New York',
 'The Flowers of War',
 "Surf's Up",
 'The Stepford Wives',
 'Black Hawk Down',
 'The Campaign',
 'The Fifth Element',
 'Sex and the City 2',
 'The Road to El Dorado',
 'Ice Age: Continental Drift',
 'Cinderella',
 'The Lovely Bones',
 'Finding Nemo',
 'The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'Seventh Son',
 'Lara Croft: Tomb Raider',
 'Transcendence',
 'Jurassic Park III',
 'Rise of the Planet of the Apes',
 'The Spiderwick Chronicles',
 'A Good Day to Die Hard',
 'The Alamo',
 'The Incredibles',
 'Cutthroat Island',
 'Percy Jackson & the Olympians: The Lightning Thief',
 'Men in Black',
 'Toy Story 2',
 'Unstoppable',
 'Rush Hour 2',
 'What Lies Beneath',
 'Cloudy with a Chance of Meatballs',
 'Ice Age: Dawn of the Dinosaurs',
 'The Secret Life of Walter Mitty',
 "Charlie's Angels",
 'The Departed',
 'Mulan',
 'Tropic Thunder',
 'The Girl with the Dragon Tattoo',
 'Die Hard: With a Vengeance',
 'Sherlock Holmes',
 'Ben-Hur',
 'Atlantis: The Lost Empire',
 'Alvin and the Chipmunks: The Road Chip',
 'Valkyrie',
 "You Don't Mess with the Zohan",
 'Pixels',
 'A.I. Artificial Intelligence',
 'The Haunted Mansion',
 'Contact',
 'Hollow Man',
 'The Interpreter',
 'Percy Jackson: Sea of Monsters',
 'Lara Croft Tomb Raider: The Cradle of Life',
 'Now You See Me 2',
 'The Saint',
 'Spy Game',
 'Mission to Mars',
 'Rio',
 'Bicentennial Man',
 'Volcano',
 "The Devil's Own",
 'K-19: The Widowmaker',
 'Conan the Barbarian',
 'Cinderella Man',
 'The Nutcracker: The Untold Story',
 'Seabiscuit',
 'Twister',
 'Cast Away',
 'Happy Feet',
 'The Bourne Supremacy',
 'Air Force One',
 "Ocean's Eleven",
 'The Three Musketeers',
 'Hotel Transylvania',
 'Enchanted',
 'Safe House',
 '102 Dalmatians',
 'Tower Heist',
 'The Holiday',
 'Enemy of the State',
 "It's Complicated",
 "Ocean's Thirteen",
 'Open Season',
 'Divergent',
 'Enemy at the Gates',
 'The Rundown',
 'Last Action Hero',
 'Memoirs of a Geisha',
 'The Fast and the Furious: Tokyo Drift',
 'Arthur Christmas',
 'Meet Joe Black',
 'Collateral Damage',
 'All That Jazz',
 'Mirror Mirror',
 'Scott Pilgrim vs. the World',
 'The Core',
 'Nutty Professor II: The Klumps',
 'Scooby-Doo',
 'Dredd',
 'Click',
 'Creepshow',
 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 'Jumper',
 'Hellboy II: The Golden Army',
 'Zodiac',
 'The 6th Day',
 'Bruce Almighty',
 'The Expendables',
 'Mission: Impossible',
 'The Hunger Games',
 'The Hangover Part II',
 'Batman Returns',
 'Over the Hedge',
 'Lilo & Stitch',
 "Charlotte's Web",
 'Deep Impact',
 'RED 2',
 'The Longest Yard',
 'Alvin and the Chipmunks: Chipwrecked',
 'Grown Ups 2',
 'Get Smart',
 "Something's Gotta Give",
 'Shutter Island',
 'Four Christmases',
 'Robots',
 'Face/Off',
 'Bedtime Stories',
 'Road to Perdition',
 'Just Go with It',
 'Con Air',
 'Eagle Eye',
 'Cold Mountain',
 'The Book of Eli',
 'Flubber',
 'The Haunting',
 'Space Jam',
 'The Pink Panther',
 'The Day the Earth Stood Still',
 'Conspiracy Theory',
 'Fury',
 'Six Days Seven Nights',
 'Yogi Bear',
 'Spirit: Stallion of the Cimarron',
 'Zookeeper',
 'Lost in Space',
 'The Manchurian Candidate',
 'DÃ©jÃ  Vu',
 'Hotel Transylvania 2',
 'Fantasia 2000',
 'The Time Machine',
 'Mighty Joe Young',
 'Swordfish',
 'The Legend of Zorro',
 'What Dreams May Come',
 'Little Nicky',
 'The Brothers Grimm',
 'Mars Attacks!',
 'Evolution',
 'The Edge',
 'Surrogates',
 'Thirteen Days',
 'Daylight',
 'Walking With Dinosaurs',
 'Battlefield Earth',
 'Looney Tunes: Back in Action',
 'Nine',
 'Timeline',
 'The Postman',
 'Babe: Pig in the City',
 'The Last Witch Hunter',
 'Red Planet',
 'Arthur and the Invisibles',
 'Oceans',
 'A Sound of Thunder',
 'Pompeii',
 'Top Cat Begins',
 'A Beautiful Mind',
 'The Lion King',
 'Journey 2: The Mysterious Island',
 'Cloudy with a Chance of Meatballs 2',
 'Red Dragon',
 'Hidalgo',
 'Jack and Jill',
 '2 Fast 2 Furious',
 'The Little Prince',
 'The Invasion',
 'The Adventures of Rocky & Bullwinkle',
 'The Secret Life of Pets',
 'The League of Extraordinary Gentlemen',
 'Despicable Me 2',
 'Independence Day',
 'The Lost World: Jurassic Park',
 'Madagascar',
 'Children of Men',
 'X-Men',
 'Wanted',
 'The Rock',
 'Ice Age: The Meltdown',
 '50 First Dates',
 'Hairspray',
 'Exorcist: The Beginning',
 'Inspector Gadget',
 'Now You See Me',
 'Grown Ups',
 'The Terminal',
 'Hotel for Dogs',
 'Vertical Limit',
 "Charlie Wilson's War",
 'Shark Tale',
 'Dreamgirls',
 'Be Cool',
 'Munich',
 'Tears of the Sun',
 'Killers',
 'The Man from U.N.C.L.E.',
 'Spanglish',
 'Monster House',
 'Bandits',
 'First Knight',
 'Anna and the King',
 'Immortals',
 'Hostage',
 'Titan A.E.',
 'Hollywood Homicide',
 'Soldier',
 'Carriers',
 'Monkeybone',
 'Flight of the Phoenix',
 'Unbreakable',
 'Minions',
 'Sucker Punch',
 'Snake Eyes',
 'Sphere',
 'The Angry Birds Movie',
 "Fool's Gold",
 'Funny People',
 'The Kingdom',
 'Talladega Nights: The Ballad of Ricky Bobby',
 'Dr. Dolittle 2',
 'Braveheart',
 'Jarhead',
 'The Simpsons Movie',
 'The Majestic',
 'Driven',
 'Two Brothers',
 'The Village',
 'Doctor Dolittle',
 'Signs',
 'Shrek 2',
 'Cars',
 'Runaway Bride',
 'xXx',
 'The SpongeBob Movie: Sponge Out of Water',
 'Ransom',
 'Inglourious Basterds',
 'Hook',
 'Die Hard 2',
 'S.W.A.T.',
 'Vanilla Sky',
 'Lady in the Water',
 'AVP: Alien vs. Predator',
 'Alvin and the Chipmunks: The Squeakquel',
 'We Were Soldiers',
 'Olympus Has Fallen',
 'Star Trek: Insurrection',
 'Battle: Los Angeles',
 'Big Fish',
 'Wolf',
 'War Horse',
 'The Monuments Men',
 'The Abyss',
 'Wall Street: Money Never Sleeps',
 'Dracula Untold',
 'The Siege',
 'Stardust',
 'Seven Years in Tibet',
 'The Dilemma',
 'Bad Company',
 'Doom',
 'I Spy',
 'Underworld: Awakening',
 'Rock of Ages',
 "Hart's War",
 'Killer Elite',
 'Rollerball',
 'Ballistic: Ecks vs. Sever',
 'Hard Rain',
 'Osmosis Jones',
 "Legends of Oz: Dorothy's Return",
 'Blackhat',
 'Sky Captain and the World of Tomorrow',
 'Basic Instinct 2',
 'Escape Plan',
 'The Legend of Hercules',
 'The Sum of All Fears',
 'The Twilight Saga: Eclipse',
 'The Score',
 'Despicable Me',
 'Money Train',
 'Ted 2',
 'Agora',
 'Mystery Men',
 'Hall Pass',
 'The Insider',
 'The Finest Hours',
 'Body of Lies',
 'Dinner for Schmucks',
 'Abraham Lincoln: Vampire Hunter',
 'Entrapment',
 'The X Files',
 'The Last Legion',
 'Saving Private Ryan',
 'Need for Speed',
 'What Women Want',
 'Ice Age',
 'Dreamcatcher',
 'Lincoln',
 'The Matrix',
 'Apollo 13',
 'The Santa Clause 2',
 'Les MisÃ©rables',
 "You've Got Mail",
 'Step Brothers',
 'The Mask of Zorro',
 'Due Date',
 'Unbroken',
 'Space Cowboys',
 'Cliffhanger',
 'Broken Arrow',
 'The Kid',
 'World Trade Center',
 'Mona Lisa Smile',
 'The Dictator',
 'Eyes Wide Shut',
 'Annie',
 'Focus',
 'This Means War',
 'Blade: Trinity',
 'Red Dawn',
 'Primary Colors',
 'Resident Evil: Retribution',
 'Death Race',
 'The Long Kiss Goodnight',
 'Proof of Life',
 'Zathura: A Space Adventure',
 'Fight Club',
 'We Are Marshall',
 'Hudson Hawk',
 'Lucky Numbers',
 'I, Frankenstein',
 'Oliver Twist',
 'Elektra',
 'Sin City: A Dame to Kill For',
 'Random Hearts',
 'Everest',
 'Perfume: The Story of a Murderer',
 'Austin Powers in Goldmember',
 'Astro Boy',
 'Jurassic Park',
 'Wyatt Earp',
 'Clear and Present Danger',
 'Dragon Blade',
 'Little Man',
 'U-571',
 'The American President',
 'The Love Guru',
 '3000 Miles to Graceland',
 'The Hateful Eight',
 'Blades of Glory',
 'Hop',
 '300',
 'Meet the Fockers',
 'Marley & Me',
 'The Green Mile',
 'Wild Hogs',
 'Chicken Little',
 'Gone Girl',
 'The Bourne Identity',
 'GoldenEye',
 "The General's Daughter",
 'The Truman Show',
 'The Prince of Egypt',
 'Daddy Day Care',
 '2 Guns',
 'Cats & Dogs',
 'The Italian Job',
 'Two Weeks Notice',
 'Antz',
 'Couples Retreat',
 'Days of Thunder',
 'Cheaper by the Dozen 2',
 'Maze Runner: The Scorch Trials',
 'Eat Pray Love',
 'The Family Man',
 'RED',
 'Any Given Sunday',
 'The Horse Whisperer',
 'Collateral',
 'The Scorpion King',
 'Ladder 49',
 'Jack Reacher',
 'Deep Blue Sea',
 'This Is It',
 'Contagion',
 'Kangaroo Jack',
 'Coraline',
 'The Happening',
 'Man on Fire',
 'The Shaggy Dog',
 'Starsky & Hutch',
 'Jingle All the Way',
 'Hellboy',
 'A Civil Action',
 'ParaNorman',
 'The Jackal',
 'Paycheck',
 'Up Close & Personal',
 'The Tale of Despereaux',
 'The Tuxedo',
 'Under Siege 2: Dark Territory',
 'Jack Ryan: Shadow Recruit',
 'Joy',
 'London Has Fallen',
 'Alien: Resurrection',
 'Shooter',
 'The Boxtrolls',
 'Practical Magic',
 'The Lego Movie',
 'Miss Congeniality 2: Armed and Fabulous',
 'Reign of Fire',
 'Gangster Squad',
 'Year One',
 'Invictus',
 'State of Play',
 'Duplicity',
 'My Favorite Martian',
 'The Sentinel',
 'Planet 51',
 'Star Trek: Nemesis',
 'Intolerable Cruelty',
 'Trouble with the Curve',
 'Edge of Darkness',
 'The Relic',
 'Analyze That',
 'Righteous Kill',
 'Mercury Rising',
 'The Soloist',
 'The Legend of Bagger Vance',
 'Almost Famous',
 'Garfield: A Tail of Two Kitties',
 'xXx: State of the Union',
 'Priest',
 'Sinbad: Legend of the Seven Seas',
 'Event Horizon',
 'Dragonfly',
 'The Black Dahlia',
 'Flyboys',
 'The Last Castle',
 'Supernova',
 "Winter's Tale",
 'The Mortal Instruments: City of Bones',
 'Meet Dave',
 'Dark Water',
 'Edtv',
 'Inkheart',
 'The Spirit',
 'Mortdecai',
 'In the Name of the King: A Dungeon Siege Tale',
 'Beyond Borders',
 'The Monkey King 2',
 'The Great Raid',
 'Deadpool',
 'Holy Man',
 'American Sniper',
 'Goosebumps',
 'Just Like Heaven',
 'The Flintstones in Viva Rock Vegas',
 'Rambo III',
 'Leatherheads',
 'The Ridiculous 6',
 'Did You Hear About the Morgans?',
 'The Internship',
 'Resident Evil: Afterlife',
 'Red Tails',
 "The Devil's Advocate",
 "That's My Boy",
 'DragonHeart',
 'After the Sunset',
 'Ghost Rider: Spirit of Vengeance',
 "Captain Corelli's Mandolin",
 'The Pacifier',
 'Walking Tall',
 'Forrest Gump',
 'Alvin and the Chipmunks',
 'Meet the Parents',
 'Pocahontas',
 'Superman',
 'The Nutty Professor',
 'Hitch',
 'George of the Jungle',
 'American Wedding',
 'Captain Phillips',
 'Date Night',
 'Casper',
 'The Equalizer',
 'Maid in Manhattan',
 'Crimson Tide',
 'The Pursuit of Happyness',
 'Flightplan',
 'Disclosure',
 'City of Angels',
 'Kill Bill: Vol. 1',
 'Bowfinger',
 'Kill Bill: Vol. 2',
 'Tango & Cash',
 'Death Becomes Her',
 'Shanghai Noon',
 'Executive Decision',
 "Mr. Popper's Penguins",
 'The Forbidden Kingdom',
 'Free Birds',
 'AlienÂ³',
 'Evita',
 'Ronin',
 'The Ghost and the Darkness',
 'Paddington',
 'The Watch',
 'The Hunted',
 'Instinct',
 'Stuck on You',
 'Semi-Pro',
 'The Pirates! In an Adventure with Scientists!',
 'Changeling',
 'Chain Reaction',
 'The Fan',
 'The Phantom of the Opera',
 'Elizabeth: The Golden Age',
 'Ã†on Flux',
 'Gods and Generals',
 'Turbulence',
 'Imagine That',
 'Muppets Most Wanted',
 'Thunderbirds',
 'Burlesque',
 'A Very Long Engagement',
 'Lolita',
 'D-Tox',
 'Blade II',
 'Seven Pounds',
 'Bullet to the Head',
 'The Godfather: Part III',
 'Elizabethtown',
 'You, Me and Dupree',
 'Superman II',
 'Gigli',
 "All the King's Men",
 'Shaft',
 'Anastasia',
 'Moulin Rouge!',
 'Domestic Disturbance',
 'Black Mass',
 'Flags of Our Fathers',
 'Law Abiding Citizen',
 'Grindhouse',
 'Beloved',
 'Lucky You',
 'Catch Me If You Can',
 'Zero Dark Thirty',
 'The Break-Up',
 'Mamma Mia!',
 "Valentine's Day",
 'The Dukes of Hazzard',
 'The Thin Red Line',
 'The Change-Up',
 'Man on the Moon',
 'Casino',
 'From Paris with Love',
 'Bulletproof Monk',
 'Me, Myself & Irene',
 'Barnyard',
 'Deck the Halls',
 'The Twilight Saga: New Moon',
 'Shrek',
 'The Adjustment Bureau',
 'Robin Hood: Prince of Thieves',
 'Jerry Maguire',
 'Ted',
 'As Good as It Gets',
 'Patch Adams',
 'Anchorman 2: The Legend Continues',
 'Mr. Deeds',
 'Super 8',
 'Erin Brockovich',
 'How to Lose a Guy in 10 Days',
 '22 Jump Street',
 'Interview with the Vampire',
 'Yes Man',
 'Central Intelligence',
 'Stepmom',
 "Daddy's Home",
 'Into the Woods',
 'Inside Man',
 'Payback',
 'Congo',
 'We Bought a Zoo',
 'Knowing',
 'Failure to Launch',
 'The Ring Two',
 'Crazy, Stupid, Love.',
 'Garfield',
 'Christmas with the Kranks',
 'Moneyball',
 'Outbreak',
 'Non-Stop',
 'Race to Witch Mountain',
 'V for Vendetta',
 'Shanghai Knights',
 'Curious George',
 'Herbie Fully Loaded',
 "Don't Say a Word",
 'Hansel & Gretel: Witch Hunters',
 'Unfaithful',
 'I Am Number Four',
 'Syriana',
 '13 Hours: The Secret Soldiers of Benghazi',
 'The Book of Life',
 'Firewall',
 'Absolute Power',
 'G.I. Jane',
 'The Game',
 'Silent Hill',
 'The Replacements',
 'American Reunion',
 'The Negotiator',
 'Into the Storm',
 'Beverly Hills Cop III',

In [ ]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [ ]:
recommend("Avatar")

Aliens
Aliens vs Predator: Requiem
Falcon Rising
Titan A.E.
Independence Day

In [ ]:
recommend('Spectre')

Skyfall
Quantum of Solace
Never Say Never Again
From Russia with Love
Octopussy

In [ ]:
recommend('The Expendables')

Street Fighter
Men of War
The Warrior's Way
DOA: Dead or Alive
The Last Dragon